In [1]:
import numpy as np
import pandas as pd

In [2]:
import os

if os.getcwd().endswith('notebooks'):
    os.chdir('..')
    print('Changed directory to', os.getcwd())

Changed directory to /morphoml

# Only extract necessary metadata

In [3]:
df_meta = pd.read_csv('./data/metadata/metadata_valid_morphid.tsv',
                      sep='\t', index_col=0)
print(df_meta.shape)
df_meta.head()

(73627, 30)

,RA,DEC,D25,redshift,GalSize_kpc,D_Mpc,d_pix_kpc,reduced_chi_square,logM_bayes,logM_bayes_err,...,ML_zibetti,RA_leda,DEC_leda,D25_leda,R25_leda,pa_leda,id_gz1,dist_gz1,id_gz2,dist_gz2
SDSS_ID,,,,,,,,,,,,,,,,,,,,,
1237662301367173202,231.31860,41.34601,0.512861,0.0761,48.655727,326.142854,0.632474,3.980811,10.328326,0.057643,...,2.553861,231.318646,41.346012,0.516416,4.677351,52.77,552094,0.000016,131054,0.191547
1237662301905813735,236.00985,39.28830,0.446684,0.0685,38.145197,293.571417,0.569310,0.537818,9.834362,0.037180,...,1.054716,236.009916,39.288303,0.441570,2.897344,131.08,572069,0.000104,177157,0.094953
1237662534360301834,237.49500,9.27861,0.630957,0.0390,30.677076,167.142861,0.324133,0.280960,9.851568,0.057156,...,0.805557,237.494992,9.278609,0.629506,1.312200,155.89,577778,0.000041,37238,0.000052
1237662500543987740,242.00880,36.05398,0.562341,0.0658,46.129129,282.000016,0.546870,1.192938,10.439780,0.044860,...,1.775870,242.008785,36.053987,0.557186,1.315225,63.55,596382,0.000021,76320,0.000036
1237662474235085097,251.31645,25.60003,0.512861,0.0681,43.540800,291.857134,0.565985,1.540025,9.999021,0.040437,...,1.205651,251.316496,25.600029,0.510505,3.539973,42.81,624773,0.000070,62784,0.079806

In [4]:
print(df_meta.columns)

Index(['RA', 'DEC', 'D25', 'redshift', 'GalSize_kpc', 'D_Mpc', 'd_pix_kpc',
       'reduced_chi_square', 'logM_bayes', 'logM_bayes_err', 'L_g_bayes',
       'L_g_bayes_err', 'hasimg', 'isgalaxy', 'M_bayes', 'M_bayes_err',
       'ML_bayes', 'ML_bayes_err', 'mag_g', 'mag_i', 'ML_zibetti', 'RA_leda',
       'DEC_leda', 'D25_leda', 'R25_leda', 'pa_leda', 'id_gz1', 'dist_gz1',
       'id_gz2', 'dist_gz2'],
      dtype='object')

In [9]:
# Keep only subset, and translate names
colmap = {'ML_bayes': 'M/L', 'L_g_bayes': 'L_g', 'D_Mpc': 'distance_Mpc', 
          'GalSize_kpc': 'galsize_kpc'}
df_meta = df_meta[list(colmap.keys())].rename(columns=colmap)
df_meta.head()

                          M/L           L_g  distance_Mpc  galsize_kpc
SDSS_ID
1237662301367173202  2.398229  8.880467e+09    326.142854    48.655727
1237662301905813735  0.974585  7.007162e+09    293.571417    38.145197
1237662534360301834  0.678322  1.047446e+10    167.142861    30.677076
1237662500543987740  1.574709  1.748155e+10    282.000016    46.129129
1237662474235085097  1.076603  9.267565e+09    291.857134    43.540800

In [10]:
df_meta.to_csv('./data/metadata/metadata.tsv', sep='\t')